#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 27 14:10:29 2023

@author: aswinpaul
"""
import numpy as np
import gymnasium as gym

from minigrid.wrappers import FullyObsWrapper

env = gym.make("MiniGrid-Empty-5x5-v0", render_mode = "rgb_array")
env = FullyObsWrapper(env) 

#trials
seedloops = 10
episodes = 50

data = np.zeros((seedloops,episodes))


for sl in range(seedloops):
    
    print('sl:', sl)

    # Changing random seeds
    rseed = sl;
    np.random.seed(rseed)
    
    for ts in range(episodes):

        done = False
        tau = 0
        
        observation, info = env.reset(seed = rseed)
        score = 0

        while(done == False):
            tau += 1
            
            action = np.random.randint(0,3)  

            # Fetching next-state reward from envrionment-function
            observation, reward, terminated, truncated, info = env.step(action)

            reward = 100 if reward > 0 else -1
            score += reward
    
            if terminated or truncated:
                done = True
    
        data[sl][ts] = score
        
# %%

with open('data_trial_random.npy', 'wb') as f:
    np.save(f, data)